version: "3"
services:
  backend:
    build:
      context: ./mail-backend
    ports:
      - "8080:8080"
    networks:
      - app_network
  frontend:
    build:
      context: ./mail-client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    ports:
      - "4080:4080"
    environment:
      ZINC_DATA_PATH: "/data"
      ZINC_FIRST_ADMIN_USER: "admin"
      ZINC_FIRST_ADMIN_PASSWORD: "Complexpass#123"
    volumes:
      - "./data:/data"
    networks:
      - app_network
networks:
  app_network:
